/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminPrescriptionsRouteImport } from './routes/admin.prescriptions'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'

const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPrescriptionsRoute = AdminPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/prescription': typeof PrescriptionRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/prescription': typeof PrescriptionRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/prescription': typeof PrescriptionRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/prescriptions': typeof AdminPrescriptionsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/dashboard'
    | '/login'
    | '/prescription'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/prescriptions'
    | '/category/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/dashboard'
    | '/login'
    | '/prescription'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/prescriptions'
    | '/category/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/dashboard'
    | '/login'
    | '/prescription'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/prescriptions'
    | '/category/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PrescriptionRoute: typeof PrescriptionRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/prescriptions': {
      id: '/admin/prescriptions'
      path: '/prescriptions'
      fullPath: '/admin/prescriptions'
      preLoaderRoute: typeof AdminPrescriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPrescriptionsRoute: typeof AdminPrescriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPrescriptionsRoute: AdminPrescriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PrescriptionRoute: PrescriptionRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
